# Generated by Django 4.1.5 on 2023-01-26 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=250)),
                ('pic_alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadMenu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
                ('price', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('load_type', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=255)),
                ('shop_keeper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
